name: typecheck-next-api

on:
  push:
    branches:
      - master
      - dc
      - tap
      - xd
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - docs/**
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: 'next/api/package-lock.json'

      - name: Install dependencies
        run: |
          cd next/api
          npm ci

      - name: Typecheck
        run: |
          cd next/api
          npm run typecheck
